export const REMOVE_ITEM = "REMOVE_ITEM";
export const INCREASE_ITEM = "INCREASE_ITEM";
export const DECREASE_ITEM = "DECREASE_ITEM";
export const CLEAR_ALL_ITEMS = "CLEAR_ALL_ITEMS";
export const GET_ALL_ITEMS = "GET_ALL_ITEMS";
export const LOADING_ITEM = "LOADING_ITEM";
export const GET_TOTAL_ITEMS = "GET_TOTAL_ITEMS";
