export const ADD_CART = "ADD_CART";
export const UPDATE_CART = "UPDATE_CART";
export const DELETE_CART = "DELETE_CART";
export const UPDATE_TOTAL_ITEMS = "UPDATE_TOTAL_ITEMS";
export const UPDATE_TOTAL_AMOUNT = "UPDATE_TOTAL_AMOUNT";
