export const LOADING_PRODUCTS_BEGIN = "LOADING_PRODUCTS_BEGIN";
export const LOADING_PRODUCTS_END = "LOADING_PRODUCTS_END";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
